### ISSUE TITLE
Border-image doesn't get prefixed in WebKit

### ISSUE THREAD

**Issue by jingidy** [LeaVerou/prefixfree#102]
border-image doesn't get translate to -webkit-border-image.
Test case:
`border-image: url(path/to/img.png) 10 10 10 10;`

In Safari 6 and Chrome 21, the generated CSS is the same, whereas it should be
`-webkit-border-image: url(path/to/img.png) 10 10 10 10;`

In Firefox, the CSS is correctly generated as
`-moz-border-image: url(path/to/img.png) 10 10 10 10;`

**Comment by LeaVerou** [comment]
The reason is that WebKit supports the unprefixed `border-image` as well. When -prefix-free sees that the unprefixed feature is supported too, it doesn't prefix it.
If you want to explicitly use the prefixed version, you can use `-*-` as a prefix, which will be replaced with the current browser's prefix on runtime. If you do that however, make sure you provide an unprefixed alternative as well, otherwise your code will break in the future. Also, `-*-` was added very recently, so if you want to use that, make sure you have the latest version.
