### ISSUE TITLE
Linear Gradient not working on iPad

### ISSUE THREAD

**Issue by DNZ1809** [LeaVerou/prefixfree#103]
Hi,

It seems prefix-free isn't working for the linear-gradient on iPad.

I was using:
`background: linear-gradient(to bottom, #77b3c7 3%,#006f95 100%); /* W3C */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#77b3c7', endColorstr='#006f95',GradientType=0 ); /* IE6-9 */`

It works in every browser but not on our iPad 2, I had to add the following prefix:
`background: -webkit-linear-gradient(top, #77b3c7 0%,#006f95 100%); /* Chrome10+,Safari5.1+ */`

**Comment by LeaVerou** [comment]
Many browser versions don't support `to bottom` and need `top` instead, not just iPad Safari. I suggest you use both syntaxes, unprefixed, the one with `to bottom` being second. Remember: -prefix-free will just prefix when/if needed, not fix other browser inconsistencies (though I might do that in the future, with plugins).

In this case, I suggest you use angles (90deg) which are handled by -prefix-free automatically. They are the only thing that it handles besides prefixing, only because there is no way to utilize the cascade for this. For more info look here: http://lea.verou.me/2012/07/important-prefix-free-update/

**Comment by DNZ1809** [comment]
Didn't know that. Thank you kindly for the help.
