### ISSUE TITLE
Cache manifest

### ISSUE THREAD

**Issue by oscar-broman** [LeaVerou/prefixfree#107]
When using a cache manifest, PrefixFree will always load the file from network.

**Comment by ghost** [comment]
In my opinion prefix free is always reloading (loading 2 times) all the CSS resources, not only when using a cache manifest, but I think this is not a bug but the only way to analyize all the css rules from javascript (but I hope that there's some other way, this is the only reason I'm not using prefixfree anymore)

**Comment by LeaVerou** [comment]
What makes you think so?

**Comment by ghost** [comment]
This: 

--> http://i.snag.gy/Sanjn.jpg (screenshoot)

I can see these extra xhr request for all the CSS in Chrome Developer Tools, Firebug etc.

And following lines in prefixfree.js (StyleFix 1.0.3 & PrefixFree 1.0.7)

``` javascript
/*LINE 37*/         process = function() {
                var css = xhr.responseText;
//...
//...
/*LINE 73*/  try {
            xhr.open('GET', url);
            xhr.send(null);
        } catch (e) {
            // Fallback to XDomainRequest if available
            if (typeof XDomainRequest != "undefined") {
                xhr = new XDomainRequest();
                xhr.onerror = xhr.onprogress = function() {};
                xhr.onload = process;
                xhr.open("GET", url);
                xhr.send(null);
            }
        }

```

Anyway I have to say that:

1) Obviously all resources are already cached when the js invoke the xhr call so the overhead is very small, but as you know XHR requests are always really sent to the server (and waited) , also when we have the same URL-key arleady cached (except old version of IE where we have the bug of AJAX caching) so  if prefixfree script is not propley loaded in a deferred way a little delay on page load can occur, and if you have a lot of CSS resources and a bit of latency this can easily mean also +1s 

2) This bheaivor is present in all the javascript polyfills/tools related to CSS  I used, e.g I discovered it in Flexie.js first time, code in flexie.js is pretty explicative:

``` javascript
function loadStyleSheet(url) {
            var xhr = getXHRObject(),
                responseText;

            xhr.open("GET", url, FALSE);
            xhr.send();

            responseText = (xhr.status === 200) ? xhr.responseText : EMPTY_STRING;

            if (url === window.location.href) {
                responseText = parseInlineStyles(responseText);
            }

            return responseText;
        }

```

3) I'm sure there's a good pratical reason why all CSS polyfills developers are not using something like the following to parse CSS :

``` javascript
 sheets = document.styleSheets;
  for(var c = 0; c < sheets.length; c++) {
    var rules = sheets[c].rules || sheets[c].cssRules;
    for(var r = 0; r < rules.length; r++) {
    if ($.browser.msie) {
      var cssText = cssRule.style.cssText.toLowerCase();
    } else {
      var cssText = cssRule.cssText;
    }
```

(if there isn't a reason please try if using this instead of or fallbacked by xhr can improve the performance)

**Comment by oscar-broman** [comment]
Here's an iPhone using AppCache, when loading the page:

See the bottom 2 rows.

![Web Inspector](http://puu.sh/16xKD)

**Comment by LeaVerou** [comment]
1 & 2: Yes, that's how it's supposed to work. I thought you meant the whole CSS is reloaded, not just a small request to check if it's recent enough. Keep in mind that until that request returns, you still have the non-prefixed CSS active. It's not like people see your page with no styles or anything.
3: Yes, there is. Browsers drop things they don't understand from cssText, so it's pretty useless here. Unfortunately.

**Comment by oscar-broman** [comment]
After looking in the Apache logs, I can see it never actually sends a request to the server - the Web Inspector's output is a little ambiguous!
