### ISSUE TITLE
background-size support

### ISSUE THREAD

**Issue by FrederickGeek8** [LeaVerou/prefixfree#136]
Support needs to be added for <code>background-size</code>.

**Comment by deweydb** [comment]
+1

**Comment by LeaVerou** [comment]
Lolwut? `background-size` doesn’t need any prefixes…
But even if it did, they should be added in browsers that need them as properties are detected automatically.

**Comment by deweydb** [comment]
In latest version of chrome you can't do:
background-size: cover;
You must do:
-webkit-background-size: cover;
Isn't this exactly the type of thing prefixfree is supposed to solve?

**Comment by LeaVerou** [comment]
Yes, you can. Do you have a specific example where it’s not working? And what do you mean by latest version of Chrome? I have 37.0.2062.124 and it seems to work just fine.

**Comment by deweydb** [comment]
Ah, i stand corrected, it was a mistake with my class inheritance.  Sorry.

**Comment by LeaVerou** [comment]
No worries, it happens :)

**Comment by deweydb** [comment]
Sorry to re-bother you with this.  But assuming that in some older versions of chrome you did need that prefix, shouldn't that be part of prefixfree? will simply using: background-size: cover;
fail in some old version of chrome?

**Comment by LeaVerou** [comment]
There is no such thing as a specific property being part of -prefix-free or not. -prefix-free doesn’t store a list of properties, it gets it from the browser. So yes, there shouldn’t be a problem with older versions of Chrome. My point earlier was that it doesn't need a prefix in current browsers, so if you use the dev tools to inspect and don't see a prefix, it's probably because the browser supports the property unprefixed.

The only issue is when properties are supported both with a prefix and without, with different syntaxes. In that case -prefix-free will fail, and you have to include the prefixes manually (`filter`/`-webkit-filter` is one such example).

**Comment by deweydb** [comment]
Shit, that's a brilliant solution to the problem, i did not realize it worked that way.  Thank you!

**Comment by LeaVerou** [comment]
Thanks! I should write it up somewhere on the website as it seems that everyone that starts using PF is under the same confusion.
Btw there is a list of functions, @rules, pseudos, as you can't get a list of those from the browser (it still does feature testing to see which ones of those need a prefix). But you can for properties.
