### ISSUE TITLE
Google fonts bug

### ISSUE THREAD

**Issue by verlok** [LeaVerou/prefixfree#15]
I'm getting the following error with prefixfree enabled on my site:

XMLHttpRequest cannot load http://fonts.googleapis.com/css?family=Ubuntu+Condensed. Origin http://www.andreaverlicchi.eu is not allowed by Access-Control-Allow-Origin

All ok if prefixfree is disabled.

Check it here:
http://www.andreaverlicchi.eu (prefixfree is now disabled by default, waiting for fixes)
http://www.andreaverlicchi.eu/?prefixfree=enable

Thank you in advance.

**Comment by LeaVerou** [comment]
Is it fixed now?

Btw (and that's completely unrelated to prefixfree) I would recommend using the @import that Google Fonts provides. As it currently stands, if you want to change the font, you also have to change the markup, which is a kinda bad practice.

**Comment by verlok** [comment]
Right. Thank you for the advice. 
Btw, how can I get the latest version of prefixfree without having to pull it and upload it to my site at every update?

Inviato da iPhone

Il giorno 17/ott/2011, alle ore 03:04, Lea Veroureply@reply.github.com ha scritto:

**Comment by verlok** [comment]
Fixed!

**Comment by dellsala** [comment]
For anyone else with this problem and looking at this issue, the solution to this problem was changed here https://github.com/LeaVerou/prefixfree/pull/39

**Comment by thsur** [comment]
As dellsala said, the issue is fixed - but don't use 'alternate' as part of the attribute string, as this prevents Chrome/FF/IE from loading the fonts. Try 'prefetch' instead, as in:
&lt;link href="http://fonts.googleapis.com/..." rel="stylesheet prefetch" title="fonts" type="text/css" /&gt; 

See also:
http://blog.whatwg.org/the-road-to-html-5-link-relations
