### ISSUE TITLE
Help with Linear Gradients and Wordpress

### ISSUE THREAD

**Issue by ghost** [LeaVerou/prefixfree#158]
I'm trying to use pff in my wordpress blog. I've downloaded and included the scripts, but the linear gradients seem to not working. I tried in the Test Drive page and is not doing anything for the sample codes below:
1. background: linear-gradient(center top, #FFFFFF 0%, #F9F9F9 50%, #F1F1F1 50.1%, #EFEFEF 100%); should have been
   /_background: -moz-linear-gradient(top, #FFFFFF 0%, #F9F9F9 50%, #F1F1F1 50.1%, #EFEFEF 100%) repeat scroll 0 0 transparent;_/
2. background: linear-gradient(top, #FFFFFF ,#E6E6E6); should change
   /_background: -moz-linear-gradient(top, #FFFFFF, #E6E6E6);/_FF*/ 

thanks in advance

**Comment by LeaVerou** [comment]
Hi there,

a) You tested with a browser that supports gradients unprefixed, so there's nothing for pff to do.
b) You’re using the older syntax, but browsers supporting unprefixed gradients use the new one (`to bottom` instead of `top`). If you want full coverage, you should use both, as pff only adds prefixes when needed, doesn't tweak syntax (except linear gradient angles, since there's no way to use the cascade for that)

Cheers
