### ISSUE TITLE
Linear-Gradient webkit issue

### ISSUE THREAD

**Issue by getcatalyzed** [LeaVerou/prefixfree#174]
Having an issue where linear-gradients are not getting prefixed in Safari 7.0, Mobile Safari on iOS7 and Chrome Version 30.0.1599.101.  Worked fine in previous version of Safari / mobile Safari.

**Comment by LeaVerou** [comment]
Yes, because these browsers don't need prefixes for gradients :p 
You do need to use the newer syntax to take advantage of that though, which is probably why you think your gradients are not working.

**Comment by getcatalyzed** [comment]
I pulled up my page in all of these browsers, and the gradients are not working unless I prefix them myself in my code.

**Comment by LeaVerou** [comment]
Yes, because browsers that support unprefixed gradients still support the older syntax if you prefix them. Unprefixed gradients require the newer syntax. You're using the older syntax, which is why your gradients don't work without the prefix. You should use both syntaxes, since -prefix-free only adds prefixes when needed, it wont transform your syntax ([except angles](http://lea.verou.me/2012/07/important-prefix-free-update/))

**Comment by getcatalyzed** [comment]
Ok - I didn't realize that the overall syntax changed.  I will look up the new syntax.  It's unfortunate that this code will now need to be duplicated as the old syntax won't work unprefixed, and the new syntax won't work prefixed for older browsers!

**Comment by LeaVerou** [comment]
Yeah, it's a shame indeed, and it was very difficult to make -prefix-free work with both syntaxes, as I outlined in that post :(
When possible, you can use angles, which -prefix-free will transform though.

**Comment by getcatalyzed** [comment]
Sounds great. Thank you for the direction on this and for prefix free in general!
