### ISSUE TITLE
animations not getting prefixed in Chrome

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/prefixfree#188]
It seems that Chrome falsely reports supporting unprefixed animations but does nothing with them, so -prefix-free gets confused and doesn't prefix them.

Test code: http://dabblet.com/gist/9165666

Not sure how to fix this right now, so any ideas would be greatly appreciated.

Edit: This only seems to happen if the "Enable Experimental Web Platform Features" flag is enabled, so not as critical as I originally thought.

**Comment by TylerEich** [comment]
As of Google Chrome v36.0.1935.0 (1935.0) on Mac OS X 10.9.2 (13C64) with "Enable Experimental Web Platform Features" set to `true`, this issue is no longer exhibited.

**Comment by LeaVerou** [comment]
Great!

**Comment by Yeswanth-JG** [comment]
@LeaVerou I don't know where to ask.! So, I am just dropping here..!

Can i knw the mechanism of `-prefix-free-` to detect the browser & version number.

Since, on changing the `Enable Experimental Web Platform Features` to `true`, the version of Chrome also changing. So, if we get the same, we can prefix required props with `-webkit-`

> Sorry for any wrongs, duplicates!

**Comment by TylerEich** [comment]
Prefixfree doesn't detect browser and version number.

Regardless, this issue no longer exists on the latest Chrome versions; no fix is needed.

**Comment by Yeswanth-JG** [comment]
:+1: @TylerEich  Thanks!
