### ISSUE TITLE
Does not work with radial-gradient

### ISSUE THREAD

**Issue by jczimm** [LeaVerou/prefixfree#201]
As specified [here](https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient), `radial-gradient` needs prefixes.  As a `background-image`, **-prefix-free** does not add the necessary CSS prefixes.

**Comment by LeaVerou** [comment]
Yes, it does. You just need to use the old & new syntaxes (unprefixed) alongside. E.g.

``` css
background: radial-gradient(top left, circle, red, black);
background: radial-gradient(circle at top left, red, black);
```

**Comment by jczimm** [comment]
Oh, ok.  Thanks

**Comment by LeaVerou** [comment]
Note that in cases where the old & new syntax are the same, you don’t need two versions. For example:

``` css
background: radial-gradient(red, black);
```

or

``` css
background: radial-gradient(farthest-side, red, black);
```

etc.

In general, -prefix-free doesn't edit syntax, it only adds prefixes, otherwise it would be incredibly heavy. If you're using a feature a lot, and you need two syntaxes, it's very easy to write a plugin, like I did here: http://lea.verou.me/css3patterns (view source, it's under the inclusion of PF).
