### ISSUE TITLE
Strange behaviour in dev tools

### ISSUE THREAD

**Issue by Yojimb0** [LeaVerou/prefixfree#32]
I'll try to explain it with words, but I made a picture more understandable.

=> http://www.yojimbo.fr/_images/prefixfree_issue.png

I set up 2 test-cases :
- http://www.yojimbo.fr/test_prefixfree.html
- http://www.yojimbo.fr/test_without_prefixfree.html

Step by Step :
- In both cases, I do a right-click on the section tag (Big grey square) -> inspect
- then Dev Tools open in Elements panel, where i can see DOM on the left, and Styles applied to selection on the right.
- In the right subpannel, we can see which file is the origin of the shown CSS, it's where the difference appears. Without PrefixFree, I get the classic behaviour : the CSS file is show, i can click on it and live edit it in Ressources panel. But With PrefixFree, it's the HTML file which is shown, and whene i click on, i still go to Ressource panel, and Chrome doesn't show me the CSS, but the HTML file -> and here, when i click on the CSS file, and try to edit it, it doesn't work :( !

Maybe it's not a PrefixFree problem, that's why I didn't make an issue here at first. Maybe it's a local problem (But my coworkers have the same) ... I don't know, but thanks for the help !

**Comment by LeaVerou** [comment]
It looks like a Web Inspector bug to me: The live editor only accounts for the downloaded HTML and not the generated one. Since -prefix-free (and any other script that manipulates CSS) has to convert linked stylesheets to embedded ones on the fly (due to CSSOM limitations), Web Inspector doesn't "catch" the generated stylesheet.

I'd recommend you file this as a Webkit dev tools bug. Mention that it not only causes issues with -prefix-free but most likely also with LESS.js and any script that works in that way. Good luck!

**Comment by Yojimb0** [comment]
At first I thougth it was that, but it's the same bug in Firebug (showing a link to HTML instead of CSS, except live edit still works), and on various versions of Chrome :(

**Comment by LeaVerou** [comment]
It _is_ supposed to show a link to HTML, as the linked stylesheet is now converted to an embedded one (inside `<style>...</style>` tags. That's not a bug. Webkit Inspector's inability to let you edit is.

**Comment by Yojimb0** [comment]
Aaaaaawwwh ! That's true. My mistake here. Anyway thanks for the support, to do all that you've done and still keeping time to answer dumbs like me is really nice :D

**Comment by LeaVerou** [comment]
Thank _you_ for trying it out and reporting bugs :)
