### ISSUE TITLE
Prefixfree doesn't support the columns property

### ISSUE THREAD

**Issue by ghost** [LeaVerou/prefixfree#54]
Prefixfree doesn't support columns rules from CSS3 :

http://www.w3.org/TR/css3-multicol/

It should be interesting to add it :-)

**Comment by LeaVerou** [comment]
In which way doesn't it support them?

**Comment by ghost** [comment]
When I add

```
columns: 2;
column-gap: 2em;
```

to my CSS

`column-gap` is well prefixed but not `columns`. So I can't see anything in my browser (Firefox 10.0.2 under MAC OS X).

**Comment by LeaVerou** [comment]
Confirmed.

Turns out this is happening because `columns` isn't following the naming conventions of the rest of CSS for shorthands, so it's not detected.

I will fix this eventually (it's not trivial), but in the meantime, you can use `column-width` or `column-count`, which should get properly prefixed.

**Comment by SimonSapin** [comment]
I see the same bug, but even the longhands are not un-prefixed: http://dabblet.com/gist/3175716

**Comment by LeaVerou** [comment]
That’s a different bug, and not even a -prefix-free one. Inline styles are not run through -prefix-free in dabblet. If you move it to the CSS panel, it works fine.
