### ISSUE TITLE
Not working with linear-gradient

### ISSUE THREAD

**Issue by tnguyen14** [LeaVerou/prefixfree#90]
My Chrome browser says the linear-gradient property is invalid. Firefox says the same thing too.
Not sure if this is a bug with prefixfree or with browser support.

Here's the CSS:  

`background: linear-gradient (to bottom, rgba(0, 0, 0, 0.1) 0%, rgba(250, 250, 250, 0) 50%, rgba(0, 0, 0, 0.1) 100%);`

Here's the link to JSFiddle:
http://jsfiddle.net/tringuyen/BMvse/

**Comment by NHQ** [comment]
Edited to remove the risk of spreading obsolete information.

**Comment by LeaVerou** [comment]
There are several issues with this fiddle:
1. -prefix-free is not even included. JSFiddle does not bundle -prefix-free by default. [dabblet](http://dabblet.com) does, so if you want to avoid including it every time, you might want to look into that.
2. Your syntax is invalid. There is no comma between `to bottom` and the color stops.
3. I’d advise you don’t use `to bottom` yet, many browsers aren’t yet up to date with the newer syntax. -prefix-free will just add the prefix if needed, it won’t account for entirely different syntax.

@NHQ: Please don’t spread false information. WebKit has been supporting `-webkit-linear-gradient` for ages. `-webkit-gradient` is obsolete and has been so for a while. Also, `linear-gradient` is not Firefox’s syntax, it’s the standard syntax that every browser supports. Moreover, prefixes on standard features are not needed when using -prefix-free (`-webkit-gradient` of course would still need one, since it’s a proprietary feature).

**Comment by tnguyen14** [comment]
Hi,
1. My apologies. I added -prefix-free but forgot to press on "update" before closing the window, so it's not included. It is now. 
2. According to the Mozilla Developer Network CSS guide, it is okay to have a comma after `to bottom`, see here: https://developer.mozilla.org/en/CSS/linear-gradient. Would you advise that this is not a good resource to use? I've been going here for guide on the right CSS syntax.
3. Instead of `to bottom` , what would you advise I should use? I tried `top`, but that doesn't work either.
4. If you check the fiddle http://jsfiddle.net/tringuyen/BMvse/1 again, it is still not working.

**Comment by LeaVerou** [comment]
1. I mean there is no comma in your code and there should be one.
2. It doesn't because of the other mistakes. Also, keep in mind that `top` or `to bottom` isn't even needed, it's the default.

You have a space between `linear-gradient` and `(`.

If you fix the above, it's working fine.

Please, before reporting a -prefix-free bug, check if your code is working WITH a prefix. Your code wasn't working even if you added a prefix manually, so it was obviously not a -prefix-free bug.

**Comment by TrigZu** [comment]
Lea, I would like to use -prefix-free for phone web development, but I've this issue with gradients.  Almost all phones use WebKit for their browser, but older Droid-phones only support the -webkit-gradient(linear/radial) syntax, not the -webkit-linear/radial-gradient syntax.  I could of course set the -webkit-gradient syntax myself, but I feel like that kind of defeats the purpose of using something like -prefix-free.  Is this a legacy code issue that I should just deal with, or is it possible for you to add support for this syntax?  

The reason I ask this is because even though -webkit-linear-gradient has been supported by WebKit "for ages" (a little under two years now), smartphones older than 2-years of age aren't capable of recognizing the syntax; and as far as I'm aware the browser/WebKit engine doesn't auto-update on most phones.  According to the internet (which doesn't lie), the average lifespan of smartphones is 2-3 years, which means that any pre-2011 purchased Droid-phone won't properly display gradients (although to be honest, it's likely said phones will be replaced within the next year).  I tried to get an estimate as to how many phone-users this issue would currently affect, but a number like that is hard to calculate; however, I'd guess it's at least 10% of the phone market for the next year (again, a guess).  I'm not sure that amount of people warrants supporting legacy code, but just a suggestion if you can manage it.  Thanks!

**Comment by LeaVerou** [comment]
Hi,

I might add this as a plugin at some point, but it's not high priority. I'd suggest you just use -webkit-gradient along with the proper syntax. Sorry.
