### ISSUE TITLE
Firefox 13

### ISSUE THREAD

**Issue by ghost** [LeaVerou/prefixfree#91]
As of Firefox 13, -moz- prefix is no longer supported on box-shadow and border-radius. Unless the unprefixed version is also used, the effect won't be applied.

https://developer.mozilla.org/en/Firefox_13_for_developers

Prefixfree needs to be updated so that when those selectors are being used, it does not try and add the -moz- selectors if fits a version newer than firefox 12.

**Comment by LeaVerou** [comment]
`border-radius` and `box-shadow` have been unprefixed for ages, way before Firefox 12. If something breaks when using them, it’s probably not due to -prefix-free. Also, -prefix-free doesn't need to be updated every time a new property gets unprefixed, that’s the whole point of using it.
If you still think you’ve discovered a bug in -prefix-free, please provide a testcase.
